version: 2.1

orbs:
  node: circleci/node@1.1.6
jobs:
  install-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn build
            - run: tar -zcf indebtedless-$CIRCLE_TAG.$CIRCLE_BUILD_NUM.tar.gz ./build
            - persist_to_workspace:
                root: .
                paths:
                  - ./indebtedless-$CIRCLE_TAG.$CIRCLE_BUILD_NUM.tar.gz
  deploy:
    steps:
      - add_ssh_keys:
          fingerprints:
            - 74:06:b1:7e:14:88:7a:48:9f:15:7d:56:ea:05:09:6a
      - attach_workspace:
          at: .
      - run:
          name: "Deploy to digital ocean server"
          command: |
            scp ./indebtedless-$CIRCLE_TAG.$CIRCLE_BUILD_NUM.tar.gz root@142.93.5.41:/var/www/indebtedless.com/

workflows:
  build-and-deploy:
    jobs:
      - install-and-test:
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
            branches:
              ignore: /.*/
      - build:
          requires:
            - install-and-test
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
            branches:
              ignore: /.*/